#!/usr/bin/env bash
# a Bash script that transfers a file from our client to a server
# Requirements:
# - Accepts 4 parameters
#   1. The path to the file to be transferred
#   2. The IP of the server we want to transfer the file to
#   3. The username scp connects with
#   4. The path to the SSH private key that scp uses
# - Display Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY if less than 4 parameters passed
# - scp must transfer the file to the user home directory ~/
# - Strict host key checking must be disabled when using scp
# Function to display usage message
usage() {
    echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
}

# Check if number of arguments is less than 4
if [ "$#" -lt 4 ]; then
    usage
    exit 1
fi

# Assigning arguments to variables
file_path=$1
server_ip=$2
username=$3
ssh_key=$4

# Transfer file using scp with strict host key checking disabled
scp -o StrictHostKeyChecking=no -i "$ssh_key" "$file_path" "$username@$server_ip":~/

